name: google_places_search
description: "This project demonstrates finding places using Google API"

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.4.1
  freezed: ^2.4.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
